#!/bin/bash
# start.sh — Fabric Minecraft Server Launcher
# Auto-detects: tmux > screen > nohup
# Usage: ./start.sh {start|stop|restart|status|console}
#
# This file is auto-generated by fabric-setup.sh
# You can also just drop this into any Fabric server directory.

set -e

SESSION_NAME="minecraft-fabric"
JAVA_XMS="${JAVA_XMS:-1G}"
JAVA_XMX="${JAVA_XMX:-2G}"
JAVA_FLAGS="-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200"
PID_FILE=".server.pid"

# Auto-detect server jar
if [ -z "$SERVER_JAR" ]; then
    SERVER_JAR=$(ls -1 fabric-server-*.jar 2>/dev/null | head -1)
fi
if [ -z "$SERVER_JAR" ]; then
    echo "[ERROR] Tidak ada fabric-server-*.jar di direktori ini."
    exit 1
fi

# Detect available multiplexer
detect_backend() {
    if command -v tmux &>/dev/null; then
        echo "tmux"
    elif command -v screen &>/dev/null; then
        echo "screen"
    else
        echo "nohup"
    fi
}

BACKEND="${FORCE_BACKEND:-$(detect_backend)}"

is_running() {
    case "$BACKEND" in
        tmux)
            tmux has-session -t "$SESSION_NAME" 2>/dev/null
            ;;
        screen)
            screen -list | grep -q "$SESSION_NAME"
            ;;
        nohup)
            [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null
            ;;
    esac
}

do_start() {
    if is_running; then
        echo "[*] Server sudah jalan ($BACKEND: $SESSION_NAME)"
        return
    fi
    echo "[*] Starting Fabric server..."
    echo "    Jar: $SERVER_JAR"
    echo "    RAM: $JAVA_XMS - $JAVA_XMX"
    echo "    Backend: $BACKEND"

    case "$BACKEND" in
        tmux)
            tmux new-session -d -s "$SESSION_NAME" "java $JAVA_FLAGS -Xms$JAVA_XMS -Xmx$JAVA_XMX -jar $SERVER_JAR nogui"
            echo "    Attach: tmux attach -t $SESSION_NAME"
            echo "    Detach: Ctrl+B, D"
            ;;
        screen)
            screen -dmS "$SESSION_NAME" java $JAVA_FLAGS -Xms"$JAVA_XMS" -Xmx"$JAVA_XMX" -jar "$SERVER_JAR" nogui
            echo "    Attach: screen -r $SESSION_NAME"
            echo "    Detach: Ctrl+A, D"
            ;;
        nohup)
            mkdir -p logs
            nohup java $JAVA_FLAGS -Xms"$JAVA_XMS" -Xmx"$JAVA_XMX" -jar "$SERVER_JAR" nogui > logs/console.log 2>&1 &
            echo $! > "$PID_FILE"
            echo "    Log: tail -f logs/console.log"
            ;;
    esac

    sleep 3
    if is_running; then
        echo "[*] Server started successfully."
    else
        echo "[ERROR] Server gagal start. Cek log."
        exit 1
    fi
}

do_stop() {
    if ! is_running; then
        echo "[*] Server tidak jalan."
        rm -f "$PID_FILE"
        return
    fi
    echo "[*] Stopping server..."

    case "$BACKEND" in
        tmux)
            tmux send-keys -t "$SESSION_NAME" "save-all" Enter
            sleep 2
            tmux send-keys -t "$SESSION_NAME" "stop" Enter
            ;;
        screen)
            screen -S "$SESSION_NAME" -p 0 -X stuff "save-all^M"
            sleep 2
            screen -S "$SESSION_NAME" -p 0 -X stuff "stop^M"
            ;;
        nohup)
            if [ -f "$PID_FILE" ]; then
                kill "$(cat "$PID_FILE")" 2>/dev/null || true
            fi
            ;;
    esac

    for i in $(seq 1 30); do
        if ! is_running; then
            echo "[*] Server stopped."
            rm -f "$PID_FILE"
            return
        fi
        sleep 1
    done

    echo "[WARN] Force killing..."
    case "$BACKEND" in
        tmux)   tmux kill-session -t "$SESSION_NAME" 2>/dev/null || true ;;
        screen) screen -S "$SESSION_NAME" -X quit 2>/dev/null || true ;;
        nohup)  kill -9 "$(cat "$PID_FILE")" 2>/dev/null || true ;;
    esac
    rm -f "$PID_FILE"
}

do_status() {
    if is_running; then
        echo "[*] Server status: RUNNING ($BACKEND: $SESSION_NAME)"
    else
        echo "[*] Server status: STOPPED"
    fi
}

do_console() {
    if ! is_running; then
        echo "[*] Server tidak jalan."
        exit 1
    fi
    case "$BACKEND" in
        tmux)
            echo "[*] Attaching (Ctrl+B, D to detach)..."
            sleep 1
            tmux attach -t "$SESSION_NAME"
            ;;
        screen)
            echo "[*] Attaching (Ctrl+A, D to detach)..."
            sleep 1
            screen -r "$SESSION_NAME"
            ;;
        nohup)
            echo "[*] Tailing console log (Ctrl+C to stop tailing)..."
            tail -f logs/console.log
            ;;
    esac
}

case "${1}" in
    start)          do_start ;;
    stop)           do_stop ;;
    restart)        do_stop; sleep 2; do_start ;;
    status)         do_status ;;
    console|attach) do_console ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|console}"
        echo ""
        echo "Env vars:"
        echo "  JAVA_XMS       Min RAM  (default: 1G)"
        echo "  JAVA_XMX       Max RAM  (default: 2G)"
        echo "  SERVER_JAR     Path to jar (auto-detected)"
        echo "  FORCE_BACKEND  tmux|screen|nohup (auto-detected)"
        echo ""
        echo "Examples:"
        echo "  ./start.sh start"
        echo "  JAVA_XMX=4G ./start.sh start"
        echo "  FORCE_BACKEND=nohup ./start.sh start"
        ;;
esac
