#!/bin/bash
# start.sh — Fabric Minecraft Server Launcher
# Auto-detects: tmux > screen > nohup
# Usage: ./start.sh {start|stop|restart|status|console}
#
# This file is auto-generated by fabric-setup.sh
# You can also just drop this into any Fabric server directory.

set -e

SESSION_NAME="minecraft-fabric"
JAVA_XMS="${JAVA_XMS:-1G}"
JAVA_XMX="${JAVA_XMX:-2G}"
JAVA_FLAGS="-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200"
PID_FILE=".server.pid"
SERVER_PROPERTIES="server.properties"

# --- Config helpers: read/write server.properties ---
prop_get() {
    local key="$1"
    grep "^${key}=" "$SERVER_PROPERTIES" 2>/dev/null | tail -1 | cut -d= -f2-
}

prop_set() {
    local key="$1"
    local value="$2"
    if grep -q "^${key}=" "$SERVER_PROPERTIES" 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$SERVER_PROPERTIES"
    else
        echo "${key}=${value}" >> "$SERVER_PROPERTIES"
    fi
}

# --- Server port ---
SERVER_PORT="${SERVER_PORT:-$(prop_get server-port)}"
SERVER_PORT="${SERVER_PORT:-25565}"

# --- Pre-start: kill anything on the configured port ---
kill_port() {
    local port="$1"
    local pids
    pids=$(ss -tlnp 2>/dev/null | grep ":${port} " | grep -oP 'pid=\K[0-9]+' | sort -u)
    if [ -n "$pids" ]; then
        echo "[!] Port $port sudah dipakai. Killing: $pids"
        kill -9 $pids 2>/dev/null || true
        sleep 2
    fi
}

# Auto-detect server jar
if [ -z "$SERVER_JAR" ]; then
    SERVER_JAR=$(ls -1 fabric-server-*.jar 2>/dev/null | head -1)
fi
if [ -z "$SERVER_JAR" ]; then
    echo "[ERROR] Tidak ada fabric-server-*.jar di direktori ini."
    exit 1
fi

# Detect available multiplexer (verify it actually works)
detect_backend() {
    if command -v tmux &>/dev/null; then
        if tmux new-session -d -s "__test_$$__" 2>/dev/null; then
            tmux kill-session -t "__test_$$__" 2>/dev/null
            echo "tmux"
            return
        fi
    fi
    if command -v screen &>/dev/null; then
        if screen -dmS "test_$$" true 2>/dev/null; then
            screen -S "test_$$" -X quit 2>/dev/null
            echo "screen"
            return
        fi
    fi
    echo "nohup"
}

BACKEND="${FORCE_BACKEND:-$(detect_backend)}"

is_running() {
    case "$BACKEND" in
        tmux)
            tmux has-session -t "$SESSION_NAME" 2>/dev/null
            ;;
        screen)
            screen -list | grep -q "$SESSION_NAME"
            ;;
        nohup)
            [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null
            ;;
    esac
}

do_start() {
    if is_running; then
        echo "[*] Server sudah jalan ($BACKEND: $SESSION_NAME)"
        return
    fi

    # Handle port config
    if [ -n "$SERVER_PORT" ]; then
        prop_set "server-port" "$SERVER_PORT"
        kill_port "$SERVER_PORT"
    fi

    echo "[*] Starting Fabric server..."
    echo "    Jar: $SERVER_JAR"
    echo "    RAM: $JAVA_XMS - $JAVA_XMX"
    echo "    Port: $SERVER_PORT"
    echo "    Backend: $BACKEND"

    case "$BACKEND" in
        tmux)
            tmux new-session -d -s "$SESSION_NAME" "java $JAVA_FLAGS -Xms$JAVA_XMS -Xmx$JAVA_XMX -jar $SERVER_JAR nogui"
            echo "    Attach: tmux attach -t $SESSION_NAME"
            echo "    Detach: Ctrl+B, D"
            ;;
        screen)
            screen -dmS "$SESSION_NAME" java $JAVA_FLAGS -Xms"$JAVA_XMS" -Xmx"$JAVA_XMX" -jar "$SERVER_JAR" nogui
            echo "    Attach: screen -r $SESSION_NAME"
            echo "    Detach: Ctrl+A, D"
            ;;
        nohup)
            mkdir -p logs
            nohup java $JAVA_FLAGS -Xms"$JAVA_XMS" -Xmx"$JAVA_XMX" -jar "$SERVER_JAR" nogui > logs/console.log 2>&1 &
            echo $! > "$PID_FILE"
            echo "    Log: tail -f logs/console.log"
            ;;
    esac

    sleep 3
    if is_running; then
        echo "[*] Server started successfully."
    else
        echo "[ERROR] Server gagal start. Cek log."
        exit 1
    fi
}

do_stop() {
    if ! is_running; then
        echo "[*] Server tidak jalan."
        rm -f "$PID_FILE"
        return
    fi
    echo "[*] Stopping server..."

    case "$BACKEND" in
        tmux)
            tmux send-keys -t "$SESSION_NAME" "save-all" Enter
            sleep 2
            tmux send-keys -t "$SESSION_NAME" "stop" Enter
            ;;
        screen)
            screen -S "$SESSION_NAME" -p 0 -X stuff "save-all^M"
            sleep 2
            screen -S "$SESSION_NAME" -p 0 -X stuff "stop^M"
            ;;
        nohup)
            if [ -f "$PID_FILE" ]; then
                kill "$(cat "$PID_FILE")" 2>/dev/null || true
            fi
            ;;
    esac

    for i in $(seq 1 30); do
        if ! is_running; then
            echo "[*] Server stopped."
            rm -f "$PID_FILE"
            return
        fi
        sleep 1
    done

    echo "[WARN] Force killing..."
    case "$BACKEND" in
        tmux)   tmux kill-session -t "$SESSION_NAME" 2>/dev/null || true ;;
        screen) screen -S "$SESSION_NAME" -X quit 2>/dev/null || true ;;
        nohup)  kill -9 "$(cat "$PID_FILE")" 2>/dev/null || true ;;
    esac
    rm -f "$PID_FILE"
}

do_status() {
    if is_running; then
        echo "[*] Server status: RUNNING ($BACKEND: $SESSION_NAME)"
    else
        echo "[*] Server status: STOPPED"
    fi
}

do_console() {
    if ! is_running; then
        echo "[*] Server tidak jalan."
        exit 1
    fi
    case "$BACKEND" in
        tmux)
            echo "[*] Attaching (Ctrl+B, D to detach)..."
            sleep 1
            tmux attach -t "$SESSION_NAME"
            ;;
        screen)
            echo "[*] Attaching (Ctrl+A, D to detach)..."
            sleep 1
            screen -r "$SESSION_NAME"
            ;;
        nohup)
            echo "[*] Tailing console log (Ctrl+C to stop tailing)..."
            tail -f logs/console.log
            ;;
    esac
}

do_config() {
    local key="$2"
    local value="$3"

    if [ -z "$key" ]; then
        echo "Current server.properties:"
        echo "---"
        grep -v "^#" "$SERVER_PROPERTIES" | grep -v "^$" | head -20
        echo "---"
        echo "Usage: $0 config <key> <value>"
        echo ""
        echo "Common keys:"
        echo "  server-port      Port (default: 25565)"
        echo "  gamemode         survival/creative/adventure/spectator"
        echo "  difficulty       peaceful/easy/normal/hard"
        echo "  max-players      Max players"
        echo "  motd             Server name"
        echo "  online-mode      true/false"
        echo "  pvp              true/false"
        echo "  level-seed       World seed"
        echo "  level-name       World folder name"
        echo "  view-distance    Chunk render distance"
        echo "  simulation-distance"
        echo "  white-list       true/false"
        echo "  enforce-whitelist true/false"
        return
    fi

    if [ -z "$value" ]; then
        # Read mode
        local current
        current=$(prop_get "$key")
        echo "$key = ${current:-<not set>}"
    else
        # Write mode
        prop_set "$key" "$value"
        echo "[*] Set $key = $value"
    fi
}

case "${1}" in
    start)          do_start ;;
    stop)           do_stop ;;
    restart)        do_stop; sleep 2; do_start ;;
    status)         do_status ;;
    console|attach) do_console ;;
    config)         do_config "$2" "$3" "$4" ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|console|config}"
        echo ""
        echo "Commands:"
        echo "  start           Start server"
        echo "  stop            Stop server"
        echo "  restart         Restart server"
        echo "  status          Check status"
        echo "  console         View console / tail log"
        echo "  config <k> <v>  Read/set server.properties"
        echo ""
        echo "Env vars:"
        echo "  JAVA_XMS       Min RAM  (default: 1G)"
        echo "  JAVA_XMX       Max RAM  (default: 2G)"
        echo "  SERVER_PORT    Override port (auto-kill old process)"
        echo "  SERVER_JAR     Path to jar (auto-detected)"
        echo "  FORCE_BACKEND  tmux|screen|nohup (auto-detected)"
        echo ""
        echo "Examples:"
        echo "  ./start.sh start"
        echo "  JAVA_XMX=4G ./start.sh start"
        echo "  SERVER_PORT=25566 ./start.sh start"
        echo "  ./start.sh config server-port 25566"
        echo "  ./start.sh config motd \"My Cool Server\""
        echo "  ./start.sh config difficulty hard"
        ;;
esac
